module.exports = {
  eventProjection: {
    bookedBy: 0,
    ticketSellingDays: 0,
    cumulativeRevenue: 0,
    courseAnalytics: 0,
    permissions: 0,
    faq: 0,
    gallery: 0,
    belongsTo:0,
    isPromoted:0,
    promotionExpiry:0,
    promotionLevel:0
  },

  clubProjection: {
    gallery: 0,
    videos: 0,
    upcomingEvent: 0,
    team: 0,
    xAxisData: 0,
    yAxisData: 0,
    members: 0,
    adminId: 0,
    notifications: 0,
    content: 0,
    reviewBadges: 0,
    unusedBadges: 0,
    usedBadges: 0,
    proposalHistory: 0,
    undecidedProposals: 0,
    pinnedBy: 0,
    permissions: 0,
    memoryRequests: 0,
    awards: 0,
    processedPayments: 0,
  },

  communityProjection: {
    content: 0,
    members: 0,
    onlineMembers: 0,
    pinnedBy: 0,
    admins: 0,
    reviewBadges: 0,
    unusedBadges: 0,
    usedBadges: 0,
    seeLessFeed: 0,
    muted: 0,
    pendingRequests: 0,
    banList: 0,
  },
};